import RegistrationManager from "./RegistrationManager.json";

export const registrationManagerMetadata = {
	address: "0x5Fa0cBcdaFb91207a70D86Ff9c75EE68A0c0b8f1" as `0x${string}`,
	abi: RegistrationManager.abi as IRegistrationManagerABI["abi"],
};

// Generated by https://quicktype.io

export interface IRegistrationManagerABI {
	abi: ABI[];
}

export interface ABI {
	inputs: Put[];
	stateMutability?: StateMutability;
	type: Type;
	anonymous?: boolean;
	name?: string;
	outputs?: Put[];
}

export interface Put {
	internalType: string;
	name: string;
	type: string;
	indexed?: boolean;
}

export enum StateMutability {
	Nonpayable = "nonpayable",
	Payable = "payable",
	View = "view",
}

export enum Type {
	Constructor = "constructor",
	Event = "event",
	Function = "function",
}
